- name: "Create Config Directory"
  become: yes
  file:
    path: "{{ wireguard_config_directory }}"
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: "Delete Configuration Files"
  become: yes
  vars:
    interface: "{{ item }}"
  file:
    path: "{{ wireguard_config_directory }}/{{ item.name }}.conf"
    state: absent
  with_items: "{{ wireguard_interfaces }}"
  when:
    - wireguard_interfaces is defined
    - "item.state == 'absent'"

- name: "Deploy Configuration Files"
  become: yes
  vars:
    interface: "{{ item }}"
  template:
      src: "wg.conf.j2"
      dest: "{{ wireguard_config_directory }}/{{ item.name }}.conf"
  with_items: "{{ wireguard_interfaces }}"
  when:
    - wireguard_interfaces is defined
    - "item.state == 'present'"
